[package]
name = "ceres-test-runner"
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow = "1.0"
ceres-core = { path = "../ceres-core" }

[build-dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking"] }
zip = "2.2"

[dev-dependencies]

[lints.clippy]
missing_errors_doc = "allow"
missing_panics_doc = "allow"
pedantic = "warn"
